---
# Source: nginx-helm/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-nginx-helm
  labels:
    helm.sh/chart: nginx-helm-0.1.0
    app.kubernetes.io/name: nginx-helm
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: nginx-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-nginx-helm
  labels:
    helm.sh/chart: nginx-helm-0.1.0
    app.kubernetes.io/name: nginx-helm
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-helm
    app.kubernetes.io/instance: nginx
---
# Source: nginx-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nginx-helm
  labels:
    helm.sh/chart: nginx-helm-0.1.0
    app.kubernetes.io/name: nginx-helm
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-helm
      app.kubernetes.io/instance: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-helm
        app.kubernetes.io/instance: nginx
    spec:
      serviceAccountName: nginx-nginx-helm
      securityContext:
        {}
      containers:
        - name: nginx-helm
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: nginx-helm/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "nginx-nginx-helm-test-connection"
  labels:
    helm.sh/chart: nginx-helm-0.1.0
    app.kubernetes.io/name: nginx-helm
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['nginx-nginx-helm:80']
  restartPolicy: Never
